title: Awala Specs
description: Specifications of the Awala Protocol Suite

remote_theme: "pmarsceill/just-the-docs@v0.3.3"

exclude:
  - SECURITY.md
  - vendor/

# Theme-specific options
search_enabled: true
aux_links:
  "Awala Specs on GitHub":
    - "https://github.com/AwalaNetwork/specs"
