title: Awala Specs
description: Specifications of the Awala Protocol Suite

exclude:
  - SECURITY.md
  - vendor/
  - diagrams/README.md

remote_theme: "pmarsceill/just-the-docs@v0.7.0"
# Theme-specific options
color_scheme: dark
search_enabled: true
aux_links:
  "Awala Specs on GitHub":
    - "https://github.com/AwalaNetwork/specs"
