title: Relaynet Specs
description: Specifications of the Relaynet Protocol Suite

remote_theme: pmarsceill/just-the-docs

# Theme-specific options
search_enabled: true
aux_links:
  "Relaynet Specs on GitHub":
    - "https://github.com/relaynet/specs"
